Repository ConnorDY/OSRS-Environment-Exporter, pull requests merged in 2022-09, with the labels that each got.

#136 Unlimit region IDs
  CHANGELOG.md
  src/main/kotlin/AppConstants.kt
Labels: bug fix

#135 Huge region support
  CHANGELOG.md
  src/main/kotlin/controllers/GridRegionChooserController.kt
  src/main/kotlin/controllers/LocationSearchController.kt
  src/main/kotlin/controllers/RegionChooserController.kt
  src/main/kotlin/controllers/RegionLoadingDialogHelper.kt
  src/main/kotlin/controllers/main/MainController.kt
  src/main/kotlin/controllers/main/SceneExportProgressDialogSpawner.kt
  src/main/kotlin/controllers/main/SceneLoadProgressDialogSpawner.kt
  src/main/kotlin/controllers/worldRenderer/CPUNonPriorityRenderer.kt
  src/main/kotlin/controllers/worldRenderer/Constants.kt
  src/main/kotlin/controllers/worldRenderer/GLSLPriorityRenderer.kt
  src/main/kotlin/controllers/worldRenderer/Renderer.kt
  src/main/kotlin/controllers/worldRenderer/SceneDrawListener.kt
  src/main/kotlin/controllers/worldRenderer/SceneExporter.kt
  src/main/kotlin/controllers/worldRenderer/helpers/MeshBuffers.kt
  src/main/kotlin/controllers/worldRenderer/helpers/ModelBuffers.kt
  src/main/kotlin/models/formats/FloatVectorBuffer.kt
  src/main/kotlin/models/formats/GlTFExporter.kt
  src/main/kotlin/models/formats/MaterialBuffers.kt
  src/main/kotlin/models/formats/MeshFormatExporter.kt
  src/main/kotlin/models/formats/glTF/Accessor.kt
  src/main/kotlin/models/formats/glTF/AccessorType.kt
  src/main/kotlin/models/formats/glTF/Asset.kt
  src/main/kotlin/models/formats/glTF/Attributes.kt
  src/main/kotlin/models/formats/glTF/Buffer.kt
  src/main/kotlin/models/formats/glTF/BufferTarget.kt
  src/main/kotlin/models/formats/glTF/BufferView.kt
  src/main/kotlin/models/formats/glTF/ComponentType.kt
  src/main/kotlin/models/formats/glTF/Image.kt
  src/main/kotlin/models/formats/glTF/Material.kt
  src/main/kotlin/models/formats/glTF/Mesh.kt
  src/main/kotlin/models/formats/glTF/Node.kt
  src/main/kotlin/models/formats/glTF/Primitive.kt
  src/main/kotlin/models/formats/glTF/PrimitiveMode.kt
  src/main/kotlin/models/formats/glTF/Scene.kt
  src/main/kotlin/models/formats/glTF/Texture.kt
  src/main/kotlin/models/formats/glTF/extensions/Extensions.kt
  src/main/kotlin/models/formats/glTF/extensions/KHRMaterialsSpecular.kt
  src/main/kotlin/models/formats/glTF/glTF.kt
  src/main/kotlin/models/glTF/Buffer.kt
  src/main/kotlin/models/glTF/Node.kt
  src/main/kotlin/models/glTF/glTF.kt
  src/main/kotlin/models/scene/Scene.kt
  src/main/kotlin/utils/ByteChunkBuffer.kt
  src/main/kotlin/utils/ChunkWriteListener.kt
  src/main/kotlin/utils/Utils.kt
Labels: enhancement

#138 Fix texture brightness changing between exports
  CHANGELOG.md
  src/main/kotlin/cache/definitions/TextureDefinition.kt
Labels: bug fix

#137 Merge region dialogs
  CHANGELOG.md
  src/main/kotlin/controllers/LocationSearchController.kt
  src/main/kotlin/controllers/RegionChooserController.kt
  src/main/kotlin/controllers/main/MainController.kt
Labels: enhancement

#140 Jittering camera fix for preview
  CHANGELOG.md
  src/main/kotlin/controllers/worldRenderer/Camera.kt
  src/main/kotlin/controllers/worldRenderer/GLSLPriorityRenderer.kt
  src/main/kotlin/controllers/worldRenderer/InputHandler.kt
  src/main/kotlin/controllers/worldRenderer/Renderer.kt
  src/main/resources/gpu/common.glsl
  src/main/resources/gpu/comp.glsl
  src/main/resources/gpu/comp_common.glsl
  src/main/resources/gpu/priority_render.glsl
  src/main/resources/gpu/to_screen.glsl
  src/main/resources/gpu/uniforms.glsl
Labels: bug fix

#141 Implement FOV calculation
  CHANGELOG.md
  README.md
  src/main/kotlin/controllers/AbstractSettingsDialog.kt
  src/main/kotlin/controllers/worldRenderer/Camera.kt
  src/main/kotlin/controllers/worldRenderer/Renderer.kt
  src/main/kotlin/models/config/ConfigOptionType.kt
  src/main/kotlin/models/config/ConfigOptions.kt
  src/main/kotlin/ui/NumericTextField.kt
Labels: enhancement

#146 Update locations.json with new Tombs of Amascut locations
  CHANGELOG.md
  src/main/resources/data/locations.json
Labels: enhancement

#142 Location dedup
  CHANGELOG.md
  src/main/kotlin/controllers/LocationSearchController.kt
  src/main/kotlin/ui/FilteredListModel.kt
  src/main/resources/data/locations.json
Labels: maintenance

#139 Command line interface
  CHANGELOG.md
  run.bat
  src/main/kotlin/App.kt
  src/main/kotlin/AppConstants.kt
  src/main/kotlin/CliExporter.kt
  src/main/kotlin/cache/definitions/converters/ObjectToModelConverter.kt
  src/main/kotlin/cache/loaders/OverlayLoader.kt
  src/main/kotlin/cache/loaders/SpriteLoader.kt
  src/main/kotlin/cache/loaders/TextureLoader.kt
  src/main/kotlin/cache/loaders/UnderlayLoader.kt
  src/main/kotlin/controllers/CacheChooserController.kt
  src/main/kotlin/controllers/main/CountingSceneLoadProgressListener.kt
  src/main/kotlin/controllers/main/MainController.kt
  src/main/kotlin/controllers/main/SceneLoadProgressDialogSpawner.kt
  src/main/kotlin/controllers/worldRenderer/SceneExporter.kt
  src/main/kotlin/models/StartupOptions.kt
  src/main/kotlin/utils/Utils.kt
Labels: enhancement

#150 Add release packaging script and bump version
  CHANGELOG.md
  build.gradle.kts
  package-release
  run
  run.bat
Labels: maintenance

#151 Update README with links to tutorial video + trailer
  README.md
Labels: documentation

#155 Acknowledge RuneLite license in applicable sources and distributed binaries
  src/main/kotlin/cache/ConfigType.kt
  src/main/kotlin/cache/IndexType.kt
  src/main/kotlin/cache/definitions/LocationsDefinition.kt
  src/main/kotlin/cache/definitions/ModelDefinition.kt
  src/main/kotlin/cache/definitions/ObjectDefinition.kt
  src/main/kotlin/cache/definitions/RegionDefinition.kt
  src/main/kotlin/cache/definitions/SpriteDefinition.kt
  src/main/kotlin/cache/definitions/TextureDefinition.kt
  src/main/kotlin/cache/definitions/data/FaceNormal.kt
  src/main/kotlin/cache/definitions/data/VertexNormal.kt
  src/main/kotlin/cache/loaders/LocationsLoader.kt
  src/main/kotlin/cache/loaders/ObjectLoader.kt
  src/main/kotlin/cache/loaders/OverlayLoader.kt
  src/main/kotlin/cache/loaders/RegionLoader.kt
  src/main/kotlin/cache/loaders/SpriteLoader.kt
  src/main/kotlin/cache/loaders/TextureLoader.kt
  src/main/kotlin/cache/utils/ColorPalette.kt
  src/main/kotlin/controllers/AboutController.kt
  src/main/kotlin/controllers/LicenseViewerController.kt
  src/main/kotlin/controllers/worldRenderer/GLSLPriorityRenderer.kt
  src/main/kotlin/controllers/worldRenderer/Renderer.kt
  src/main/kotlin/controllers/worldRenderer/RuneliteRenderer.kt
  src/main/kotlin/controllers/worldRenderer/entities/ComputeObj.kt
  src/main/kotlin/controllers/worldRenderer/helpers/GpuFloatBuffer.kt
  src/main/kotlin/controllers/worldRenderer/helpers/GpuIntBuffer.kt
  src/main/kotlin/controllers/worldRenderer/shaders/Shader.kt
  src/main/kotlin/controllers/worldRenderer/shaders/ShaderException.kt
  src/main/kotlin/controllers/worldRenderer/shaders/Template.kt
  src/main/kotlin/models/scene/SceneRegionBuilder.kt
  src/main/kotlin/ui/JActionLabel.kt
  src/main/kotlin/ui/JLinkLabel.kt
  src/main/resources/licenses/OpenRS-LICENSE.txt
  src/main/resources/licenses/RuneLite-LICENSE.txt
Labels: documentation
