Repository ConnorDY/OSRS-Environment-Exporter, pull requests merged in 2022-10, with the labels that each got.

#144 Show real filename and line number in shader errors
  CHANGELOG.md
  src/main/kotlin/controllers/worldRenderer/shaders/Shader.kt
  src/main/kotlin/controllers/worldRenderer/shaders/Template.kt
Labels: maintenance

#156 Include LICENSE, README.md, and CHANGELOG.md in packaged releases
  CHANGELOG.md
  README.md
  package-release
Labels: documentation

#157 Update GitHub Workflow to create packaged release ZIP instead of just the JAR file
  .github/workflows/gradle-build.yml
Labels: maintenance

#158 Add hexagon-packed dots mode to alpha type selection
  CHANGELOG.md
  README.md
  src/main/kotlin/controllers/worldRenderer/helpers/AlphaMode.kt
  src/main/resources/gpu/frag.glsl
  src/main/resources/gpu/hex_dots.glsl
Labels: enhancement
