Repository ConnorDY/OSRS-Environment-Exporter, pull requests merged in 2022-08, with the labels that each got.

#61 Update locations data with a more complete data set
  CHANGELOG.md
  src/main/kotlin/models/locations/Location.kt
  src/main/resources/data/locations.json
Labels: enhancement

#62 Bump patch version for 2.0.1 release
  CHANGELOG.md
  build.gradle.kts
  run
  run.bat
Labels: maintenance

#63 Create GitHub issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: maintenance

#65 Combine small and large comp shaders
  .github/ISSUE_TEMPLATE/bug-report.md
  src/main/kotlin/controllers/worldRenderer/Renderer.kt
  src/main/kotlin/controllers/worldRenderer/shaders/Shader.kt
  src/main/kotlin/controllers/worldRenderer/shaders/Template.kt
  src/main/resources/gpu/comp.glsl
  src/main/resources/gpu/comp_small.glsl
Labels: maintenance

#67 Clean up ColorPalette code by merging RuneLite code into it
  src/main/kotlin/cache/definitions/TextureDefinition.kt
  src/main/kotlin/cache/utils/ColorPalette.kt
  src/main/kotlin/models/glTF/MaterialBuffers.kt
  src/main/kotlin/models/scene/SceneRegionBuilder.kt
Labels: maintenance

#68 Automatically focus on the first input when opening windows
  src/main/kotlin/controllers/LocationSearchController.kt
  src/main/kotlin/controllers/RegionChooserController.kt
Labels: enhancement

#71 Make RegionDefinition tile array elements not nullable
  src/main/kotlin/cache/definitions/RegionDefinition.kt
  src/main/kotlin/cache/loaders/RegionLoader.kt
  src/main/kotlin/cache/loaders/RegionLoaderAbstractions.kt
  src/main/kotlin/models/scene/SceneRegion.kt
  src/main/kotlin/models/scene/SceneRegionBuilder.kt
Labels: maintenance

#70 Make CalcTileColor a little less mysterious
  src/main/kotlin/cache/utils/Vec3F.kt
  src/main/kotlin/models/scene/SceneRegionBuilder.kt
Labels: maintenance

#73 Refactor some colour/brightness-related code
  src/main/kotlin/controllers/MainController.kt
  src/main/kotlin/controllers/worldRenderer/Renderer.kt
  src/main/kotlin/controllers/worldRenderer/entities/Model.kt
  src/main/kotlin/controllers/worldRenderer/entities/TileModel.kt
  src/main/kotlin/controllers/worldRenderer/entities/TilePaint.kt
  src/main/kotlin/models/scene/Scene.kt
  src/main/kotlin/models/scene/SceneRegion.kt
  src/main/kotlin/models/scene/SceneRegionBuilder.kt
  src/main/kotlin/utils/MathExt.kt
Labels: maintenance

#74 Allow setting the initial region ID + radius in config
  src/main/kotlin/controllers/MainController.kt
  src/main/kotlin/controllers/worldRenderer/Renderer.kt
  src/main/kotlin/controllers/worldRenderer/WorldRendererController.kt
Labels: enhancement

#76 Bump patch version for 2.0.2 release
  CHANGELOG.md
  build.gradle.kts
  run
  run.bat
Labels: maintenance

#77 Add donate button to README
  README.md
  docs/donate-button.png
Labels: documentation

#78 Add more info to the README
  README.md
  docs/screenshot.png
Labels: documentation

#79 Provide the option to input a grid of region IDs to load
  CHANGELOG.md
  src/main/kotlin/AppConstants.kt
  src/main/kotlin/controllers/CacheChooserController.kt
  src/main/kotlin/controllers/GridRegionChooserController.kt
  src/main/kotlin/controllers/LocationSearchController.kt
  src/main/kotlin/controllers/MainController.kt
  src/main/kotlin/controllers/RegionChooserController.kt
  src/main/kotlin/controllers/worldRenderer/InputHandler.kt
  src/main/kotlin/controllers/worldRenderer/Renderer.kt
  src/main/kotlin/controllers/worldRenderer/SceneExporter.kt
  src/main/kotlin/controllers/worldRenderer/SceneUploader.kt
  src/main/kotlin/models/scene/Scene.kt
  src/main/kotlin/ui/NumericTextField.kt
  src/main/kotlin/ui/PlaceholderTextField.kt
Labels: enhancement

#80 Uppercase mnemonics and add where missing
  src/main/kotlin/controllers/CacheChooserController.kt
  src/main/kotlin/controllers/GridRegionChooserController.kt
  src/main/kotlin/controllers/LocationSearchController.kt
  src/main/kotlin/controllers/MainController.kt
  src/main/kotlin/controllers/RegionChooserController.kt
  src/main/kotlin/controllers/SettingsController.kt
Labels: bug fix

#83 Fix volcanic mine rendering + add debug menu
  CHANGELOG.md
  README.md
  src/main/kotlin/cache/definitions/ModelDefinition.kt
  src/main/kotlin/cache/definitions/converters/ObjectToModelConverter.kt
  src/main/kotlin/controllers/DebugOptionsController.kt
  src/main/kotlin/controllers/MainController.kt
  src/main/kotlin/controllers/worldRenderer/Renderer.kt
  src/main/kotlin/models/DebugOptionsModel.kt
  src/main/kotlin/models/scene/Scene.kt
  src/main/kotlin/utils/ObservableValue.kt
Labels: bug fix

#84 Check for updates after the cache chooser screen
  CHANGELOG.md
  README.md
  src/main/kotlin/controllers/MainController.kt
  src/main/kotlin/controllers/SettingsController.kt
  src/main/kotlin/models/github/GitHubRelease.kt
Labels: enhancement

#85 Bump minor version for 2.1.0 release
  CHANGELOG.md
  build.gradle.kts
  run
  run.bat
Labels: maintenance

#88 Add giants' foundry to location search + fix names for some other locations
  CHANGELOG.md
  src/main/kotlin/controllers/LocationSearchController.kt
  src/main/resources/data/locations.json
Labels: enhancement

#89 Give Uber/LengaJenga credit for reporting the missing location
  CHANGELOG.md
Labels: documentation

#86 Pull in more RuneLite changes & abstract away from GLSL a little
  CHANGELOG.md
  build.gradle.kts
  run
  src/main/kotlin/App.kt
  src/main/kotlin/cache/definitions/ModelDefinition.kt
  src/main/kotlin/cache/definitions/converters/ObjectToModelConverter.kt
  src/main/kotlin/cache/loaders/ObjectLoader.kt
  src/main/kotlin/cache/utils/FloatBufferExt.kt
  src/main/kotlin/cache/utils/IntBufferExt.kt
  src/main/kotlin/controllers/CacheChooserController.kt
  src/main/kotlin/controllers/MainController.kt
  src/main/kotlin/controllers/SettingsController.kt
  src/main/kotlin/controllers/worldRenderer/AbstractPriorityRenderer.kt
  src/main/kotlin/controllers/worldRenderer/CPUNonPriorityRenderer.kt
  src/main/kotlin/controllers/worldRenderer/Camera.kt
  src/main/kotlin/controllers/worldRenderer/Constants.kt
  src/main/kotlin/controllers/worldRenderer/GLSLPriorityRenderer.kt
  src/main/kotlin/controllers/worldRenderer/InputHandler.kt
  src/main/kotlin/controllers/worldRenderer/PriorityRenderer.kt
  src/main/kotlin/controllers/worldRenderer/Renderer.kt
  src/main/kotlin/controllers/worldRenderer/SceneExporter.kt
  src/main/kotlin/controllers/worldRenderer/SceneUploader.kt
  src/main/kotlin/controllers/worldRenderer/TextureManager.kt
  src/main/kotlin/controllers/worldRenderer/WorldRendererController.kt
  src/main/kotlin/controllers/worldRenderer/entities/ComputeObj.kt
  src/main/kotlin/controllers/worldRenderer/entities/Model.kt
  src/main/kotlin/controllers/worldRenderer/entities/Renderable.kt
  src/main/kotlin/controllers/worldRenderer/entities/TileModel.kt
  src/main/kotlin/controllers/worldRenderer/entities/TilePaint.kt
  src/main/kotlin/controllers/worldRenderer/helpers/Animator.kt
  src/main/kotlin/controllers/worldRenderer/helpers/AntiAliasingMode.kt
  src/main/kotlin/controllers/worldRenderer/helpers/GLUtil.kt
  src/main/kotlin/controllers/worldRenderer/helpers/GpuFloatBuffer.kt
  src/main/kotlin/controllers/worldRenderer/helpers/GpuIntBuffer.kt
  src/main/kotlin/controllers/worldRenderer/helpers/ModelBuffers.kt
  src/main/kotlin/controllers/worldRenderer/shaders/Shader.kt
  src/main/kotlin/models/Configuration.kt
  src/main/kotlin/models/DebugOptionsModel.kt
  src/main/kotlin/models/config/ConfigOption.kt
  src/main/kotlin/models/config/ConfigOptionType.kt
  src/main/kotlin/models/config/Configuration.kt
  src/main/kotlin/models/scene/SceneRegion.kt
  src/main/kotlin/models/scene/SceneRegionBuilder.kt
  src/main/kotlin/utils/Utils.kt
  src/main/resources/gpu/common.glsl
  src/main/resources/gpu/comp.glsl
  src/main/resources/gpu/comp_common.glsl
  src/main/resources/gpu/comp_unordered.glsl
  src/main/resources/gpu/frag.glsl
  src/main/resources/gpu/geom.glsl
  src/main/resources/gpu/priority_render.glsl
  src/main/resources/gpu/scale/bicubic.glsl
  src/main/resources/gpu/scale/xbr_lv2_common.glsl
  src/main/resources/gpu/scale/xbr_lv2_frag.glsl
  src/main/resources/gpu/scale/xbr_lv2_vert.glsl
  src/main/resources/gpu/to_screen.glsl
  src/main/resources/gpu/vert.glsl
Labels: maintenance

#93 Make config values cached (in parsed form) and observable
  CHANGELOG.md
  README.md
  src/main/kotlin/App.kt
  src/main/kotlin/cache/definitions/converters/ObjectToModelConverter.kt
  src/main/kotlin/controllers/AbstractSettingsDialog.kt
  src/main/kotlin/controllers/CacheChooserController.kt
  src/main/kotlin/controllers/DebugOptionsController.kt
  src/main/kotlin/controllers/MainController.kt
  src/main/kotlin/controllers/SettingsController.kt
  src/main/kotlin/controllers/worldRenderer/InputHandler.kt
  src/main/kotlin/controllers/worldRenderer/Renderer.kt
  src/main/kotlin/controllers/worldRenderer/WorldRendererController.kt
  src/main/kotlin/models/DebugOptionsModel.kt
  src/main/kotlin/models/config/ConfigOption.kt
  src/main/kotlin/models/config/ConfigOptions.kt
  src/main/kotlin/models/config/Configuration.kt
  src/main/kotlin/models/scene/Scene.kt
  src/main/kotlin/utils/ObservableValue.kt
Labels: maintenance

#98 Fix object rotations
  CHANGELOG.md
  src/main/kotlin/cache/definitions/ModelDefinition.kt
  src/main/kotlin/controllers/worldRenderer/CPUNonPriorityRenderer.kt
  src/main/kotlin/controllers/worldRenderer/entities/Entity.kt
  src/main/kotlin/controllers/worldRenderer/entities/Model.kt
  src/main/kotlin/controllers/worldRenderer/entities/Renderable.kt
  src/main/kotlin/controllers/worldRenderer/entities/StaticObject.kt
  src/main/kotlin/models/scene/SceneRegionBuilder.kt
  src/main/resources/gpu/priority_render.glsl
Labels: bug fix

#94 Hide hidden settings in settings dialog
  src/main/kotlin/controllers/SettingsController.kt
Labels: bug fix

#95 Allow `gradle run` (& simplify java params)
  build.gradle.kts
  run
  run.bat
Labels: maintenance

#96 Small GLTF exporter optimisations
  CHANGELOG.md
  src/main/kotlin/models/glTF/Buffer.kt
  src/main/kotlin/models/glTF/FloatVectorBuffer.kt
  src/main/kotlin/models/glTF/MaterialBuffers.kt
  src/main/kotlin/models/glTF/glTF.kt
  src/main/kotlin/utils/ByteChunkBuffer.kt
Labels: enhancement

#97 Move animator timing into another thread
  CHANGELOG.md
  src/main/kotlin/controllers/worldRenderer/Renderer.kt
  src/main/kotlin/controllers/worldRenderer/helpers/Animator.kt
Labels: enhancement

#99 Alpha support in glTF; linter fixes
  CHANGELOG.md
  src/main/kotlin/models/glTF/FloatVectorBuffer.kt
  src/main/kotlin/models/glTF/MaterialBuffers.kt
  src/main/kotlin/models/glTF/glTF.kt
Labels: enhancement

#101 Fix FPS counter
  src/main/kotlin/controllers/worldRenderer/helpers/Animator.kt
Labels: bug fix

#100 Alpha hashing
  CHANGELOG.md
  README.md
  src/main/kotlin/controllers/worldRenderer/Camera.kt
  src/main/kotlin/controllers/worldRenderer/InputHandler.kt
  src/main/kotlin/controllers/worldRenderer/Renderer.kt
  src/main/kotlin/controllers/worldRenderer/helpers/AlphaMode.kt
  src/main/kotlin/models/config/ConfigOptions.kt
  src/main/resources/gpu/frag.glsl
  src/main/resources/gpu/pcg_hash.glsl
  src/main/resources/gpu/uniforms.glsl
  src/main/resources/gpu/vert.glsl
Labels: enhancement

#103 Fix ordered dithering at full opacity on some hardware; fix potential race condition in Animator thread
  src/main/kotlin/controllers/worldRenderer/helpers/Animator.kt
  src/main/resources/gpu/frag.glsl
Labels: bug fix

#106 LocationTypes discovery, wall attachment fixes, lighting fixes
  CHANGELOG.md
  src/main/kotlin/cache/LocationType.kt
  src/main/kotlin/cache/definitions/ModelDefinition.kt
  src/main/kotlin/cache/definitions/converters/ObjectToModelConverter.kt
  src/main/kotlin/cache/definitions/data/VertexNormal.kt
  src/main/kotlin/cache/loaders/ObjectLoader.kt
  src/main/kotlin/controllers/AbstractSettingsDialog.kt
  src/main/kotlin/controllers/MainController.kt
  src/main/kotlin/controllers/worldRenderer/Renderer.kt
  src/main/kotlin/controllers/worldRenderer/SceneExporter.kt
  src/main/kotlin/controllers/worldRenderer/SceneUploader.kt
  src/main/kotlin/controllers/worldRenderer/entities/GameObject.kt
  src/main/kotlin/controllers/worldRenderer/entities/Model.kt
  src/main/kotlin/controllers/worldRenderer/entities/WallDecoration.kt
  src/main/kotlin/models/DebugOptionsModel.kt
  src/main/kotlin/models/scene/Scene.kt
  src/main/kotlin/models/scene/SceneRegion.kt
  src/main/kotlin/models/scene/SceneRegionBuilder.kt
  src/main/kotlin/models/scene/SceneTile.kt
Labels: bug fix

#107 Hide priority render config option on macOS
  src/main/kotlin/models/config/ConfigOptions.kt
  src/main/kotlin/utils/Utils.kt
Labels: enhancement

#108 Fix chunk stacking when renderer is dead
  CHANGELOG.md
  src/main/kotlin/controllers/worldRenderer/Renderer.kt
  src/main/kotlin/controllers/worldRenderer/SceneExporter.kt
  src/main/kotlin/models/scene/Scene.kt
  src/main/kotlin/models/scene/SceneRegion.kt
  src/main/kotlin/models/scene/SceneTile.kt
Labels: bug fix

#109 Use lwjglx-awt 0.1.9-SNAPSHOT version
  build.gradle.kts
  src/main/kotlin/controllers/worldRenderer/Renderer.kt
Labels: bug fix

#110 Guard against divide-by-zero in UV calculation
  CHANGELOG.md
  src/main/kotlin/cache/definitions/ModelDefinition.kt
Labels: bug fix

#111 Power saving mode
  CHANGELOG.md
  README.md
  src/main/kotlin/controllers/MainController.kt
  src/main/kotlin/controllers/worldRenderer/InputHandler.kt
  src/main/kotlin/controllers/worldRenderer/Renderer.kt
  src/main/kotlin/controllers/worldRenderer/helpers/Animator.kt
  src/main/kotlin/models/DebugModel.kt
  src/main/kotlin/models/FrameRateModel.kt
  src/main/kotlin/models/config/ConfigOptions.kt
Labels: enhancement

#112 Decouple SceneExporter from Renderer
  src/main/kotlin/controllers/MainController.kt
  src/main/kotlin/controllers/worldRenderer/Renderer.kt
  src/main/kotlin/controllers/worldRenderer/SceneExporter.kt
  src/main/kotlin/models/DebugOptionsModel.kt
Labels: bug fix

#113 CacheChooserController robustness
  CHANGELOG.md
  src/main/kotlin/controllers/CacheChooserController.kt
  src/main/kotlin/controllers/GridRegionChooserController.kt
  src/main/kotlin/ui/listener/DocumentTextListener.kt
Labels: enhancement

#114 Bump minor version for 2.2.0 release
  CHANGELOG.md
  build.gradle.kts
  run
  run.bat
Labels: maintenance

#118 Add keys to set fly speed (1-9)
  CHANGELOG.md
  src/main/kotlin/controllers/worldRenderer/InputHandler.kt
Labels: enhancement

#119 Stop animation timer on MainController dispose
  CHANGELOG.md
  src/main/kotlin/controllers/MainController.kt
Labels: bug fix

#124 Handle failed mouse warps
  CHANGELOG.md
  src/main/kotlin/controllers/worldRenderer/InputHandler.kt
Labels: bug fix

#128 Add comment to Bug Report template explaining markdown checkboxes
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: documentation

#125 Scale canvas to proper width/height even under high-DPI scaling
  CHANGELOG.md
  src/main/kotlin/controllers/worldRenderer/Renderer.kt
Labels: bug fix

#117 Progress bars
  CHANGELOG.md
  src/main/kotlin/App.kt
  src/main/kotlin/cache/loaders/LocationsLoader.kt
  src/main/kotlin/cache/loaders/ModelLoader.kt
  src/main/kotlin/cache/loaders/ObjectLoader.kt
  src/main/kotlin/cache/loaders/RegionLoader.kt
  src/main/kotlin/cache/loaders/ThreadsafeLazyLoader.kt
  src/main/kotlin/controllers/CacheChooserController.kt
  src/main/kotlin/controllers/main/CountingSceneLoadProgressListener.kt
  src/main/kotlin/controllers/main/DialogSpawningSceneLoadProgressListener.kt
  src/main/kotlin/controllers/main/MainController.kt
  src/main/kotlin/controllers/main/SceneExportProgressDialogSpawner.kt
  src/main/kotlin/controllers/main/SceneLoadProgressDialogSpawner.kt
  src/main/kotlin/controllers/worldRenderer/AbstractPriorityRenderer.kt
  src/main/kotlin/controllers/worldRenderer/Constants.kt
  src/main/kotlin/controllers/worldRenderer/GLSLPriorityRenderer.kt
  src/main/kotlin/controllers/worldRenderer/InputHandler.kt
  src/main/kotlin/controllers/worldRenderer/Renderer.kt
  src/main/kotlin/controllers/worldRenderer/SceneDrawListener.kt
  src/main/kotlin/controllers/worldRenderer/SceneExporter.kt
  src/main/kotlin/controllers/worldRenderer/SceneUploader.kt
  src/main/kotlin/controllers/worldRenderer/helpers/Animator.kt
  src/main/kotlin/models/glTF/Buffer.kt
  src/main/kotlin/models/glTF/BufferView.kt
  src/main/kotlin/models/glTF/FloatVectorBuffer.kt
  src/main/kotlin/models/glTF/glTF.kt
  src/main/kotlin/models/scene/Scene.kt
  src/main/kotlin/models/scene/SceneLoadProgressListener.kt
  src/main/kotlin/ui/CancelledException.kt
  src/main/kotlin/ui/ProgressDialog.kt
  src/main/kotlin/utils/ByteChunkBuffer.kt
  src/main/kotlin/utils/ChunkWriteListener.kt
  src/main/kotlin/utils/NullProgressContainer.kt
  src/main/kotlin/utils/ProgressContainer.kt
  src/main/kotlin/utils/Utils.kt
Labels: enhancement

#129 Update screenshot
  README.md
  docs/screenshot.png
  docs/screenshot.webp
Labels: documentation

#131 Remove extra "the" in Bug Report template
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: documentation

#133 Automatic ktlintFormat via pre-commit
  .pre-commit-config.yaml
Labels: maintenance

#132 Fix gradle run version check
  build.gradle.kts
  src/main/kotlin/controllers/main/MainController.kt
  src/main/kotlin/utils/PackageMetadata.kt
Labels: maintenance
