Repository ConnorDY/OSRS-Environment-Exporter, pull requests merged in 2022-07, with the labels that each got.

#22 Update Kotlin JVM plugin to version 1.7.10
  build.gradle.kts
Labels: maintenance

#28 glTF exporter
  build.gradle.kts
  src/main/kotlin/AppConstants.kt
  src/main/kotlin/controllers/MainController.kt
  src/main/kotlin/controllers/worldRenderer/SceneExporter.kt
  src/main/kotlin/models/DebugModel.kt
  src/main/kotlin/models/glTF/Accessor.kt
  src/main/kotlin/models/glTF/AccessorType.kt
  src/main/kotlin/models/glTF/Asset.kt
  src/main/kotlin/models/glTF/Attributes.kt
  src/main/kotlin/models/glTF/Buffer.kt
  src/main/kotlin/models/glTF/BufferTarget.kt
  src/main/kotlin/models/glTF/BufferView.kt
  src/main/kotlin/models/glTF/ComponentType.kt
  src/main/kotlin/models/glTF/Image.kt
  src/main/kotlin/models/glTF/Material.kt
  src/main/kotlin/models/glTF/MaterialBuffers.kt
  src/main/kotlin/models/glTF/Mesh.kt
  src/main/kotlin/models/glTF/Node.kt
  src/main/kotlin/models/glTF/Primitive.kt
  src/main/kotlin/models/glTF/PrimitiveMode.kt
  src/main/kotlin/models/glTF/Scene.kt
  src/main/kotlin/models/glTF/Texture.kt
  src/main/kotlin/models/glTF/extensions/Extensions.kt
  src/main/kotlin/models/glTF/extensions/KHRMaterialsSpecular.kt
  src/main/kotlin/models/glTF/glTF.kt
Labels: enhancement

#33 Update, reword, and reformat CHANGELOG
  CHANGELOG.md
Labels: documentation

#39 glTF export performance improvements
  src/main/kotlin/models/glTF/Buffer.kt
  src/main/kotlin/models/glTF/FloatVectorBuffer.kt
  src/main/kotlin/models/glTF/MaterialBuffers.kt
  src/main/kotlin/models/glTF/glTF.kt
Labels: enhancement

#40 Remove gson dependency
  build.gradle.kts
  src/main/kotlin/cache/XteaManager.kt
Labels: maintenance

#41 Add location search functionality
  CHANGELOG.md
  src/main/kotlin/cache/loaders/RegionLoader.kt
  src/main/kotlin/controllers/LocationSearchController.kt
  src/main/kotlin/controllers/MainController.kt
  src/main/kotlin/controllers/RegionChooserController.kt
  src/main/kotlin/controllers/worldRenderer/Renderer.kt
  src/main/kotlin/models/DebugModel.kt
  src/main/kotlin/models/locations/Location.kt
  src/main/kotlin/models/locations/Locations.kt
  src/main/kotlin/utils/Utils.kt
  src/main/resources/data/locations.json
  src/main/resources/views/cache-chooser.fxml
  src/main/resources/views/location-search.fxml
  src/main/resources/views/main.fxml
  src/main/resources/views/region-chooser.fxml
Labels: enhancement

#42 Loader tweaks
  src/main/kotlin/cache/loaders/ModelLoader.kt
  src/main/kotlin/cache/loaders/ObjectLoader.kt
  src/main/kotlin/cache/loaders/SpriteLoader.kt
  src/main/kotlin/cache/utils/ByteBufferExt.kt
Labels: enhancement

#48 Add setting for limiting the FPS
  CHANGELOG.md
  src/main/kotlin/controllers/MainController.kt
  src/main/kotlin/controllers/RegionChooserController.kt
  src/main/kotlin/controllers/SettingsController.kt
  src/main/kotlin/controllers/worldRenderer/Renderer.kt
  src/main/kotlin/controllers/worldRenderer/SceneUploader.kt
  src/main/kotlin/controllers/worldRenderer/WorldRendererController.kt
  src/main/kotlin/controllers/worldRenderer/WorldRendererModule.kt
  src/main/resources/theme.css
  src/main/resources/views/main.fxml
  src/main/resources/views/settings.fxml
Labels: enhancement

#49 Allow region loading even when xtea is missing (but warn)
  src/main/kotlin/cache/definitions/LocationsDefinition.kt
  src/main/kotlin/cache/loaders/LocationsLoader.kt
  src/main/kotlin/cache/loaders/RegionLoader.kt
  src/main/kotlin/models/scene/SceneRegionBuilder.kt
Labels: bug fix

#50 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#51 Appearance improvements for About window
  src/main/kotlin/controllers/AboutController.kt
  src/main/resources/views/about.fxml
Labels: enhancement

#56 Add run.bat for windows users
  run.bat
Labels: maintenance
