Repository ConnorDY/OSRS-Environment-Exporter, pull requests merged in 2023-02, with the labels that each got.

#174 Fix idOffset reading in LocationsLoader
  src/main/kotlin/cache/loaders/LocationsLoader.kt
Labels: bug fix

#176 Update CHANGELOG.md and bump package version to 2.4.1
  CHANGELOG.md
  build.gradle.kts
Labels: maintenance

#177 Add configurable scale factor for export; default to 1:128
  CHANGELOG.md
  README.md
  src/main/kotlin/App.kt
  src/main/kotlin/CliExporter.kt
  src/main/kotlin/controllers/main/MainController.kt
  src/main/kotlin/controllers/worldRenderer/SceneExporter.kt
  src/main/kotlin/models/StartupOptions.kt
  src/main/kotlin/models/config/ConfigOptions.kt
  src/main/kotlin/models/config/types/ScaleMode.kt
  src/main/kotlin/models/formats/GlTFExporter.kt
  src/main/kotlin/models/formats/MaterialBuffers.kt
Labels: enhancement
